# This is an internal setup used by Good Praxis.
# If this is not run on Good Praxis servers, you need to change it.

stages:
  - build
  - test
  - review
  - deploy

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"
  DOCKER_DRIVER: overlay2

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - .npm
    - cache/Cypress
build:static:
  stage: build
  image: cypress/base:10
  before_script:
  - npm ci --cache .npm --prefer-offline
  script:
  - npx danger ci
  - npx gatsby build --prefix-paths
  artifacts:
    paths:
      - public/
  only:
  - merge_requests
  - master
  - tags

test:
  stage: test
  needs: []
  image: cypress/base:10
  script:
  - npm ci --cache .npm --prefer-offline
  - npx cypress cache path
  - npx cypress cache list
  - npm run lint
  - npm test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  artifacts:
    expire_in: 1 week
    paths:
    - cypress/screenshots
    - cypress/videos
    reports:
      junit: merged-junit.xml
  cache:
    policy: pull
  only:
    refs:
    - merge_requests
    - tags
    changes:
      - src/**/*
      - cypress/**/*

review:
  stage: review
  cache: {}
  needs: ["build:static"]
  script:
    - rsync -av --delete public /srv/nginx/pages/$CI_PROJECT_PATH_SLUG-$CI_BUILD_REF_SLUG
  dependencies:
    - build:static
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: https://$CI_PROJECT_PATH_SLUG-$CI_BUILD_REF_SLUG.$APPS_DOMAIN
    on_stop: stop_review
  only:
    - merge_requests
  tags:
    - nginx
    - review-apps
    - goodpraxis

stop_review:
  stage: review
  cache: {}
  script:
    - rm -rf public /srv/nginx/pages/$CI_PROJECT_PATH_SLUG-$CI_BUILD_REF_SLUG
  variables:
    GIT_STRATEGY: none
  when: manual
  environment:
    name: review/$CI_BUILD_REF_NAME
    action: stop
  only:
    - merge_requests
  tags:
    - nginx
    - review-apps
    - goodpraxis

deploy:staging:
  stage: deploy
  cache: {}
  script:
    - rsync -av --delete public /srv/nginx/pages/$CI_PROJECT_PATH_SLUG-staging
  dependencies:
    - build:static
  environment:
    name: staging
    url: https://$CI_PROJECT_PATH_SLUG-staging.$APPS_DOMAIN
  only:
    refs:
      - master
  tags:
    - nginx
    - review-apps
    - goodpraxis

deploy:live:
  stage: deploy
  cache: {}
  script:
    - rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --progress public/ root@$LIVE_DOMAIN:/var/www/html
  dependencies:
    - build:static
  environment:
    name: live
    url: https://$LIVE_DOMAIN
  only:
    refs:
      - master
      - alt-master
  tags:
    - nginx
    - review-apps
    - goodpraxis
  when: manual
